# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
